/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SprintsRouteImport } from './routes/sprints'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as GithubRouteImport } from './routes/github'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as DevToolsIndexRouteImport } from './routes/dev-tools/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as DevToolsUpdatesRouteImport } from './routes/dev-tools/updates'
import { Route as DevToolsTeamRouteImport } from './routes/dev-tools/team'
import { Route as DevToolsSprintsRouteImport } from './routes/dev-tools/sprints'
import { Route as DevToolsProjectsRouteImport } from './routes/dev-tools/projects'
import { Route as DevToolsIssuesRouteImport } from './routes/dev-tools/issues'
import { Route as DevToolsAnalyticsRouteImport } from './routes/dev-tools/analytics'
import { Route as ProviderGitlabIndexRouteImport } from './routes/provider/gitlab/index'
import { Route as ProviderGithubIndexRouteImport } from './routes/provider/github/index'
import { Route as ProviderGitlabProjectIdRouteImport } from './routes/provider/gitlab/$projectId'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdIssuesRouteImport } from './routes/projects/$projectId/issues'
import { Route as ProjectsProjectIdGitlabRouteImport } from './routes/projects/$projectId/gitlab'
import { Route as ProjectsProjectIdGithubRouteImport } from './routes/projects/$projectId/github'
import { Route as ProjectsProjectIdAnalyticsRouteImport } from './routes/projects/$projectId/analytics'
import { Route as ProviderGithubOwnerRepoRouteImport } from './routes/provider/github/$owner/$repo'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintsRoute = SprintsRouteImport.update({
  id: '/sprints',
  path: '/sprints',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsIndexRoute = DevToolsIndexRouteImport.update({
  id: '/dev-tools/',
  path: '/dev-tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsUpdatesRoute = DevToolsUpdatesRouteImport.update({
  id: '/dev-tools/updates',
  path: '/dev-tools/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsTeamRoute = DevToolsTeamRouteImport.update({
  id: '/dev-tools/team',
  path: '/dev-tools/team',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsSprintsRoute = DevToolsSprintsRouteImport.update({
  id: '/dev-tools/sprints',
  path: '/dev-tools/sprints',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsProjectsRoute = DevToolsProjectsRouteImport.update({
  id: '/dev-tools/projects',
  path: '/dev-tools/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsIssuesRoute = DevToolsIssuesRouteImport.update({
  id: '/dev-tools/issues',
  path: '/dev-tools/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsAnalyticsRoute = DevToolsAnalyticsRouteImport.update({
  id: '/dev-tools/analytics',
  path: '/dev-tools/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderGitlabIndexRoute = ProviderGitlabIndexRouteImport.update({
  id: '/provider/gitlab/',
  path: '/provider/gitlab/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderGithubIndexRoute = ProviderGithubIndexRouteImport.update({
  id: '/provider/github/',
  path: '/provider/github/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderGitlabProjectIdRoute = ProviderGitlabProjectIdRouteImport.update({
  id: '/provider/gitlab/$projectId',
  path: '/provider/gitlab/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdIssuesRoute = ProjectsProjectIdIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdGitlabRoute = ProjectsProjectIdGitlabRouteImport.update({
  id: '/gitlab',
  path: '/gitlab',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdGithubRoute = ProjectsProjectIdGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdAnalyticsRoute =
  ProjectsProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProviderGithubOwnerRepoRoute = ProviderGithubOwnerRepoRouteImport.update({
  id: '/provider/github/$owner/$repo',
  path: '/provider/github/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/github': typeof GithubRoute
  '/issues': typeof IssuesRoute
  '/settings': typeof SettingsRoute
  '/sprints': typeof SprintsRoute
  '/team': typeof TeamRoute
  '/updates': typeof UpdatesRoute
  '/dev-tools/analytics': typeof DevToolsAnalyticsRoute
  '/dev-tools/issues': typeof DevToolsIssuesRoute
  '/dev-tools/projects': typeof DevToolsProjectsRoute
  '/dev-tools/sprints': typeof DevToolsSprintsRoute
  '/dev-tools/team': typeof DevToolsTeamRoute
  '/dev-tools/updates': typeof DevToolsUpdatesRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/dev-tools': typeof DevToolsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/analytics': typeof ProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/github': typeof ProjectsProjectIdGithubRoute
  '/projects/$projectId/gitlab': typeof ProjectsProjectIdGitlabRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/provider/gitlab/$projectId': typeof ProviderGitlabProjectIdRoute
  '/provider/github': typeof ProviderGithubIndexRoute
  '/provider/gitlab': typeof ProviderGitlabIndexRoute
  '/provider/github/$owner/$repo': typeof ProviderGithubOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/github': typeof GithubRoute
  '/issues': typeof IssuesRoute
  '/settings': typeof SettingsRoute
  '/sprints': typeof SprintsRoute
  '/team': typeof TeamRoute
  '/updates': typeof UpdatesRoute
  '/dev-tools/analytics': typeof DevToolsAnalyticsRoute
  '/dev-tools/issues': typeof DevToolsIssuesRoute
  '/dev-tools/projects': typeof DevToolsProjectsRoute
  '/dev-tools/sprints': typeof DevToolsSprintsRoute
  '/dev-tools/team': typeof DevToolsTeamRoute
  '/dev-tools/updates': typeof DevToolsUpdatesRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/dev-tools': typeof DevToolsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/analytics': typeof ProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/github': typeof ProjectsProjectIdGithubRoute
  '/projects/$projectId/gitlab': typeof ProjectsProjectIdGitlabRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/provider/gitlab/$projectId': typeof ProviderGitlabProjectIdRoute
  '/provider/github': typeof ProviderGithubIndexRoute
  '/provider/gitlab': typeof ProviderGitlabIndexRoute
  '/provider/github/$owner/$repo': typeof ProviderGithubOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/github': typeof GithubRoute
  '/issues': typeof IssuesRoute
  '/settings': typeof SettingsRoute
  '/sprints': typeof SprintsRoute
  '/team': typeof TeamRoute
  '/updates': typeof UpdatesRoute
  '/dev-tools/analytics': typeof DevToolsAnalyticsRoute
  '/dev-tools/issues': typeof DevToolsIssuesRoute
  '/dev-tools/projects': typeof DevToolsProjectsRoute
  '/dev-tools/sprints': typeof DevToolsSprintsRoute
  '/dev-tools/team': typeof DevToolsTeamRoute
  '/dev-tools/updates': typeof DevToolsUpdatesRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/dev-tools/': typeof DevToolsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/analytics': typeof ProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/github': typeof ProjectsProjectIdGithubRoute
  '/projects/$projectId/gitlab': typeof ProjectsProjectIdGitlabRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/provider/gitlab/$projectId': typeof ProviderGitlabProjectIdRoute
  '/provider/github/': typeof ProviderGithubIndexRoute
  '/provider/gitlab/': typeof ProviderGitlabIndexRoute
  '/provider/github/$owner/$repo': typeof ProviderGithubOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/analytics'
    | '/github'
    | '/issues'
    | '/settings'
    | '/sprints'
    | '/team'
    | '/updates'
    | '/dev-tools/analytics'
    | '/dev-tools/issues'
    | '/dev-tools/projects'
    | '/dev-tools/sprints'
    | '/dev-tools/team'
    | '/dev-tools/updates'
    | '/projects/$projectId'
    | '/dev-tools'
    | '/projects'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/github'
    | '/projects/$projectId/gitlab'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/settings'
    | '/provider/gitlab/$projectId'
    | '/provider/github'
    | '/provider/gitlab'
    | '/provider/github/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/analytics'
    | '/github'
    | '/issues'
    | '/settings'
    | '/sprints'
    | '/team'
    | '/updates'
    | '/dev-tools/analytics'
    | '/dev-tools/issues'
    | '/dev-tools/projects'
    | '/dev-tools/sprints'
    | '/dev-tools/team'
    | '/dev-tools/updates'
    | '/projects/$projectId'
    | '/dev-tools'
    | '/projects'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/github'
    | '/projects/$projectId/gitlab'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/settings'
    | '/provider/gitlab/$projectId'
    | '/provider/github'
    | '/provider/gitlab'
    | '/provider/github/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/analytics'
    | '/github'
    | '/issues'
    | '/settings'
    | '/sprints'
    | '/team'
    | '/updates'
    | '/dev-tools/analytics'
    | '/dev-tools/issues'
    | '/dev-tools/projects'
    | '/dev-tools/sprints'
    | '/dev-tools/team'
    | '/dev-tools/updates'
    | '/projects/$projectId'
    | '/dev-tools/'
    | '/projects/'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/github'
    | '/projects/$projectId/gitlab'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/settings'
    | '/provider/gitlab/$projectId'
    | '/provider/github/'
    | '/provider/gitlab/'
    | '/provider/github/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AnalyticsRoute: typeof AnalyticsRoute
  GithubRoute: typeof GithubRoute
  IssuesRoute: typeof IssuesRoute
  SettingsRoute: typeof SettingsRoute
  SprintsRoute: typeof SprintsRoute
  TeamRoute: typeof TeamRoute
  UpdatesRoute: typeof UpdatesRoute
  DevToolsAnalyticsRoute: typeof DevToolsAnalyticsRoute
  DevToolsIssuesRoute: typeof DevToolsIssuesRoute
  DevToolsProjectsRoute: typeof DevToolsProjectsRoute
  DevToolsSprintsRoute: typeof DevToolsSprintsRoute
  DevToolsTeamRoute: typeof DevToolsTeamRoute
  DevToolsUpdatesRoute: typeof DevToolsUpdatesRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  DevToolsIndexRoute: typeof DevToolsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProviderGitlabProjectIdRoute: typeof ProviderGitlabProjectIdRoute
  ProviderGithubIndexRoute: typeof ProviderGithubIndexRoute
  ProviderGitlabIndexRoute: typeof ProviderGitlabIndexRoute
  ProviderGithubOwnerRepoRoute: typeof ProviderGithubOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprints': {
      id: '/sprints'
      path: '/sprints'
      fullPath: '/sprints'
      preLoaderRoute: typeof SprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/': {
      id: '/dev-tools/'
      path: '/dev-tools'
      fullPath: '/dev-tools'
      preLoaderRoute: typeof DevToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/updates': {
      id: '/dev-tools/updates'
      path: '/dev-tools/updates'
      fullPath: '/dev-tools/updates'
      preLoaderRoute: typeof DevToolsUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/team': {
      id: '/dev-tools/team'
      path: '/dev-tools/team'
      fullPath: '/dev-tools/team'
      preLoaderRoute: typeof DevToolsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/sprints': {
      id: '/dev-tools/sprints'
      path: '/dev-tools/sprints'
      fullPath: '/dev-tools/sprints'
      preLoaderRoute: typeof DevToolsSprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/projects': {
      id: '/dev-tools/projects'
      path: '/dev-tools/projects'
      fullPath: '/dev-tools/projects'
      preLoaderRoute: typeof DevToolsProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/issues': {
      id: '/dev-tools/issues'
      path: '/dev-tools/issues'
      fullPath: '/dev-tools/issues'
      preLoaderRoute: typeof DevToolsIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/analytics': {
      id: '/dev-tools/analytics'
      path: '/dev-tools/analytics'
      fullPath: '/dev-tools/analytics'
      preLoaderRoute: typeof DevToolsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/gitlab/': {
      id: '/provider/gitlab/'
      path: '/provider/gitlab'
      fullPath: '/provider/gitlab'
      preLoaderRoute: typeof ProviderGitlabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/github/': {
      id: '/provider/github/'
      path: '/provider/github'
      fullPath: '/provider/github'
      preLoaderRoute: typeof ProviderGithubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/gitlab/$projectId': {
      id: '/provider/gitlab/$projectId'
      path: '/provider/gitlab/$projectId'
      fullPath: '/provider/gitlab/$projectId'
      preLoaderRoute: typeof ProviderGitlabProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/issues': {
      id: '/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof ProjectsProjectIdIssuesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/gitlab': {
      id: '/projects/$projectId/gitlab'
      path: '/gitlab'
      fullPath: '/projects/$projectId/gitlab'
      preLoaderRoute: typeof ProjectsProjectIdGitlabRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/github': {
      id: '/projects/$projectId/github'
      path: '/github'
      fullPath: '/projects/$projectId/github'
      preLoaderRoute: typeof ProjectsProjectIdGithubRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/analytics': {
      id: '/projects/$projectId/analytics'
      path: '/analytics'
      fullPath: '/projects/$projectId/analytics'
      preLoaderRoute: typeof ProjectsProjectIdAnalyticsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/provider/github/$owner/$repo': {
      id: '/provider/github/$owner/$repo'
      path: '/provider/github/$owner/$repo'
      fullPath: '/provider/github/$owner/$repo'
      preLoaderRoute: typeof ProviderGithubOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdAnalyticsRoute: typeof ProjectsProjectIdAnalyticsRoute
  ProjectsProjectIdGithubRoute: typeof ProjectsProjectIdGithubRoute
  ProjectsProjectIdGitlabRoute: typeof ProjectsProjectIdGitlabRoute
  ProjectsProjectIdIssuesRoute: typeof ProjectsProjectIdIssuesRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdAnalyticsRoute: ProjectsProjectIdAnalyticsRoute,
  ProjectsProjectIdGithubRoute: ProjectsProjectIdGithubRoute,
  ProjectsProjectIdGitlabRoute: ProjectsProjectIdGitlabRoute,
  ProjectsProjectIdIssuesRoute: ProjectsProjectIdIssuesRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AnalyticsRoute: AnalyticsRoute,
  GithubRoute: GithubRoute,
  IssuesRoute: IssuesRoute,
  SettingsRoute: SettingsRoute,
  SprintsRoute: SprintsRoute,
  TeamRoute: TeamRoute,
  UpdatesRoute: UpdatesRoute,
  DevToolsAnalyticsRoute: DevToolsAnalyticsRoute,
  DevToolsIssuesRoute: DevToolsIssuesRoute,
  DevToolsProjectsRoute: DevToolsProjectsRoute,
  DevToolsSprintsRoute: DevToolsSprintsRoute,
  DevToolsTeamRoute: DevToolsTeamRoute,
  DevToolsUpdatesRoute: DevToolsUpdatesRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  DevToolsIndexRoute: DevToolsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProviderGitlabProjectIdRoute: ProviderGitlabProjectIdRoute,
  ProviderGithubIndexRoute: ProviderGithubIndexRoute,
  ProviderGitlabIndexRoute: ProviderGitlabIndexRoute,
  ProviderGithubOwnerRepoRoute: ProviderGithubOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
