/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpdatesIndexRouteImport } from './routes/updates/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as SprintsIndexRouteImport } from './routes/sprints/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as GithubIndexRouteImport } from './routes/github/index'
import { Route as DevToolsIndexRouteImport } from './routes/dev-tools/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as ProjectsSlugOrIdRouteImport } from './routes/projects/$slugOrId'
import { Route as ProviderGitlabIndexRouteImport } from './routes/provider/gitlab/index'
import { Route as ProviderGithubIndexRouteImport } from './routes/provider/github/index'
import { Route as ProjectsSlugOrIdIndexRouteImport } from './routes/projects/$slugOrId/index'
import { Route as DevToolsUpdatesIndexRouteImport } from './routes/dev-tools/updates/index'
import { Route as DevToolsTeamIndexRouteImport } from './routes/dev-tools/team/index'
import { Route as DevToolsSprintsIndexRouteImport } from './routes/dev-tools/sprints/index'
import { Route as DevToolsProjectsIndexRouteImport } from './routes/dev-tools/projects/index'
import { Route as DevToolsIssuesIndexRouteImport } from './routes/dev-tools/issues/index'
import { Route as DevToolsAnalyticsIndexRouteImport } from './routes/dev-tools/analytics/index'
import { Route as ProviderGitlabProjectIdRouteImport } from './routes/provider/gitlab/$projectId'
import { Route as ProjectsSlugOrIdSettingsIndexRouteImport } from './routes/projects/$slugOrId/settings/index'
import { Route as ProjectsSlugOrIdIssuesIndexRouteImport } from './routes/projects/$slugOrId/issues/index'
import { Route as ProjectsSlugOrIdGitlabIndexRouteImport } from './routes/projects/$slugOrId/gitlab/index'
import { Route as ProjectsSlugOrIdGithubIndexRouteImport } from './routes/projects/$slugOrId/github/index'
import { Route as ProjectsSlugOrIdAnalyticsIndexRouteImport } from './routes/projects/$slugOrId/analytics/index'
import { Route as ProviderGithubOwnerRepoRouteImport } from './routes/provider/github/$owner/$repo'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintsIndexRoute = SprintsIndexRouteImport.update({
  id: '/sprints/',
  path: '/sprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubIndexRoute = GithubIndexRouteImport.update({
  id: '/github/',
  path: '/github/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsIndexRoute = DevToolsIndexRouteImport.update({
  id: '/dev-tools/',
  path: '/dev-tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugOrIdRoute = ProjectsSlugOrIdRouteImport.update({
  id: '/projects/$slugOrId',
  path: '/projects/$slugOrId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderGitlabIndexRoute = ProviderGitlabIndexRouteImport.update({
  id: '/provider/gitlab/',
  path: '/provider/gitlab/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderGithubIndexRoute = ProviderGithubIndexRouteImport.update({
  id: '/provider/github/',
  path: '/provider/github/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugOrIdIndexRoute = ProjectsSlugOrIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsSlugOrIdRoute,
} as any)
const DevToolsUpdatesIndexRoute = DevToolsUpdatesIndexRouteImport.update({
  id: '/dev-tools/updates/',
  path: '/dev-tools/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsTeamIndexRoute = DevToolsTeamIndexRouteImport.update({
  id: '/dev-tools/team/',
  path: '/dev-tools/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsSprintsIndexRoute = DevToolsSprintsIndexRouteImport.update({
  id: '/dev-tools/sprints/',
  path: '/dev-tools/sprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsProjectsIndexRoute = DevToolsProjectsIndexRouteImport.update({
  id: '/dev-tools/projects/',
  path: '/dev-tools/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsIssuesIndexRoute = DevToolsIssuesIndexRouteImport.update({
  id: '/dev-tools/issues/',
  path: '/dev-tools/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsAnalyticsIndexRoute = DevToolsAnalyticsIndexRouteImport.update({
  id: '/dev-tools/analytics/',
  path: '/dev-tools/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderGitlabProjectIdRoute = ProviderGitlabProjectIdRouteImport.update({
  id: '/provider/gitlab/$projectId',
  path: '/provider/gitlab/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugOrIdSettingsIndexRoute =
  ProjectsSlugOrIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ProjectsSlugOrIdRoute,
  } as any)
const ProjectsSlugOrIdIssuesIndexRoute =
  ProjectsSlugOrIdIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => ProjectsSlugOrIdRoute,
  } as any)
const ProjectsSlugOrIdGitlabIndexRoute =
  ProjectsSlugOrIdGitlabIndexRouteImport.update({
    id: '/gitlab/',
    path: '/gitlab/',
    getParentRoute: () => ProjectsSlugOrIdRoute,
  } as any)
const ProjectsSlugOrIdGithubIndexRoute =
  ProjectsSlugOrIdGithubIndexRouteImport.update({
    id: '/github/',
    path: '/github/',
    getParentRoute: () => ProjectsSlugOrIdRoute,
  } as any)
const ProjectsSlugOrIdAnalyticsIndexRoute =
  ProjectsSlugOrIdAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => ProjectsSlugOrIdRoute,
  } as any)
const ProviderGithubOwnerRepoRoute = ProviderGithubOwnerRepoRouteImport.update({
  id: '/provider/github/$owner/$repo',
  path: '/provider/github/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/projects/$slugOrId': typeof ProjectsSlugOrIdRouteWithChildren
  '/analytics': typeof AnalyticsIndexRoute
  '/dev-tools': typeof DevToolsIndexRoute
  '/github': typeof GithubIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sprints': typeof SprintsIndexRoute
  '/team': typeof TeamIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/provider/gitlab/$projectId': typeof ProviderGitlabProjectIdRoute
  '/dev-tools/analytics': typeof DevToolsAnalyticsIndexRoute
  '/dev-tools/issues': typeof DevToolsIssuesIndexRoute
  '/dev-tools/projects': typeof DevToolsProjectsIndexRoute
  '/dev-tools/sprints': typeof DevToolsSprintsIndexRoute
  '/dev-tools/team': typeof DevToolsTeamIndexRoute
  '/dev-tools/updates': typeof DevToolsUpdatesIndexRoute
  '/projects/$slugOrId/': typeof ProjectsSlugOrIdIndexRoute
  '/provider/github': typeof ProviderGithubIndexRoute
  '/provider/gitlab': typeof ProviderGitlabIndexRoute
  '/provider/github/$owner/$repo': typeof ProviderGithubOwnerRepoRoute
  '/projects/$slugOrId/analytics': typeof ProjectsSlugOrIdAnalyticsIndexRoute
  '/projects/$slugOrId/github': typeof ProjectsSlugOrIdGithubIndexRoute
  '/projects/$slugOrId/gitlab': typeof ProjectsSlugOrIdGitlabIndexRoute
  '/projects/$slugOrId/issues': typeof ProjectsSlugOrIdIssuesIndexRoute
  '/projects/$slugOrId/settings': typeof ProjectsSlugOrIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/dev-tools': typeof DevToolsIndexRoute
  '/github': typeof GithubIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sprints': typeof SprintsIndexRoute
  '/team': typeof TeamIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/provider/gitlab/$projectId': typeof ProviderGitlabProjectIdRoute
  '/dev-tools/analytics': typeof DevToolsAnalyticsIndexRoute
  '/dev-tools/issues': typeof DevToolsIssuesIndexRoute
  '/dev-tools/projects': typeof DevToolsProjectsIndexRoute
  '/dev-tools/sprints': typeof DevToolsSprintsIndexRoute
  '/dev-tools/team': typeof DevToolsTeamIndexRoute
  '/dev-tools/updates': typeof DevToolsUpdatesIndexRoute
  '/projects/$slugOrId': typeof ProjectsSlugOrIdIndexRoute
  '/provider/github': typeof ProviderGithubIndexRoute
  '/provider/gitlab': typeof ProviderGitlabIndexRoute
  '/provider/github/$owner/$repo': typeof ProviderGithubOwnerRepoRoute
  '/projects/$slugOrId/analytics': typeof ProjectsSlugOrIdAnalyticsIndexRoute
  '/projects/$slugOrId/github': typeof ProjectsSlugOrIdGithubIndexRoute
  '/projects/$slugOrId/gitlab': typeof ProjectsSlugOrIdGitlabIndexRoute
  '/projects/$slugOrId/issues': typeof ProjectsSlugOrIdIssuesIndexRoute
  '/projects/$slugOrId/settings': typeof ProjectsSlugOrIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/projects/$slugOrId': typeof ProjectsSlugOrIdRouteWithChildren
  '/analytics/': typeof AnalyticsIndexRoute
  '/dev-tools/': typeof DevToolsIndexRoute
  '/github/': typeof GithubIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sprints/': typeof SprintsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/provider/gitlab/$projectId': typeof ProviderGitlabProjectIdRoute
  '/dev-tools/analytics/': typeof DevToolsAnalyticsIndexRoute
  '/dev-tools/issues/': typeof DevToolsIssuesIndexRoute
  '/dev-tools/projects/': typeof DevToolsProjectsIndexRoute
  '/dev-tools/sprints/': typeof DevToolsSprintsIndexRoute
  '/dev-tools/team/': typeof DevToolsTeamIndexRoute
  '/dev-tools/updates/': typeof DevToolsUpdatesIndexRoute
  '/projects/$slugOrId/': typeof ProjectsSlugOrIdIndexRoute
  '/provider/github/': typeof ProviderGithubIndexRoute
  '/provider/gitlab/': typeof ProviderGitlabIndexRoute
  '/provider/github/$owner/$repo': typeof ProviderGithubOwnerRepoRoute
  '/projects/$slugOrId/analytics/': typeof ProjectsSlugOrIdAnalyticsIndexRoute
  '/projects/$slugOrId/github/': typeof ProjectsSlugOrIdGithubIndexRoute
  '/projects/$slugOrId/gitlab/': typeof ProjectsSlugOrIdGitlabIndexRoute
  '/projects/$slugOrId/issues/': typeof ProjectsSlugOrIdIssuesIndexRoute
  '/projects/$slugOrId/settings/': typeof ProjectsSlugOrIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/projects/$slugOrId'
    | '/analytics'
    | '/dev-tools'
    | '/github'
    | '/issues'
    | '/projects'
    | '/settings'
    | '/sprints'
    | '/team'
    | '/updates'
    | '/provider/gitlab/$projectId'
    | '/dev-tools/analytics'
    | '/dev-tools/issues'
    | '/dev-tools/projects'
    | '/dev-tools/sprints'
    | '/dev-tools/team'
    | '/dev-tools/updates'
    | '/projects/$slugOrId/'
    | '/provider/github'
    | '/provider/gitlab'
    | '/provider/github/$owner/$repo'
    | '/projects/$slugOrId/analytics'
    | '/projects/$slugOrId/github'
    | '/projects/$slugOrId/gitlab'
    | '/projects/$slugOrId/issues'
    | '/projects/$slugOrId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/analytics'
    | '/dev-tools'
    | '/github'
    | '/issues'
    | '/projects'
    | '/settings'
    | '/sprints'
    | '/team'
    | '/updates'
    | '/provider/gitlab/$projectId'
    | '/dev-tools/analytics'
    | '/dev-tools/issues'
    | '/dev-tools/projects'
    | '/dev-tools/sprints'
    | '/dev-tools/team'
    | '/dev-tools/updates'
    | '/projects/$slugOrId'
    | '/provider/github'
    | '/provider/gitlab'
    | '/provider/github/$owner/$repo'
    | '/projects/$slugOrId/analytics'
    | '/projects/$slugOrId/github'
    | '/projects/$slugOrId/gitlab'
    | '/projects/$slugOrId/issues'
    | '/projects/$slugOrId/settings'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/projects/$slugOrId'
    | '/analytics/'
    | '/dev-tools/'
    | '/github/'
    | '/issues/'
    | '/projects/'
    | '/settings/'
    | '/sprints/'
    | '/team/'
    | '/updates/'
    | '/provider/gitlab/$projectId'
    | '/dev-tools/analytics/'
    | '/dev-tools/issues/'
    | '/dev-tools/projects/'
    | '/dev-tools/sprints/'
    | '/dev-tools/team/'
    | '/dev-tools/updates/'
    | '/projects/$slugOrId/'
    | '/provider/github/'
    | '/provider/gitlab/'
    | '/provider/github/$owner/$repo'
    | '/projects/$slugOrId/analytics/'
    | '/projects/$slugOrId/github/'
    | '/projects/$slugOrId/gitlab/'
    | '/projects/$slugOrId/issues/'
    | '/projects/$slugOrId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ProjectsSlugOrIdRoute: typeof ProjectsSlugOrIdRouteWithChildren
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  DevToolsIndexRoute: typeof DevToolsIndexRoute
  GithubIndexRoute: typeof GithubIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SprintsIndexRoute: typeof SprintsIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
  ProviderGitlabProjectIdRoute: typeof ProviderGitlabProjectIdRoute
  DevToolsAnalyticsIndexRoute: typeof DevToolsAnalyticsIndexRoute
  DevToolsIssuesIndexRoute: typeof DevToolsIssuesIndexRoute
  DevToolsProjectsIndexRoute: typeof DevToolsProjectsIndexRoute
  DevToolsSprintsIndexRoute: typeof DevToolsSprintsIndexRoute
  DevToolsTeamIndexRoute: typeof DevToolsTeamIndexRoute
  DevToolsUpdatesIndexRoute: typeof DevToolsUpdatesIndexRoute
  ProviderGithubIndexRoute: typeof ProviderGithubIndexRoute
  ProviderGitlabIndexRoute: typeof ProviderGitlabIndexRoute
  ProviderGithubOwnerRepoRoute: typeof ProviderGithubOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprints/': {
      id: '/sprints/'
      path: '/sprints'
      fullPath: '/sprints'
      preLoaderRoute: typeof SprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/': {
      id: '/github/'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/': {
      id: '/dev-tools/'
      path: '/dev-tools'
      fullPath: '/dev-tools'
      preLoaderRoute: typeof DevToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slugOrId': {
      id: '/projects/$slugOrId'
      path: '/projects/$slugOrId'
      fullPath: '/projects/$slugOrId'
      preLoaderRoute: typeof ProjectsSlugOrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/gitlab/': {
      id: '/provider/gitlab/'
      path: '/provider/gitlab'
      fullPath: '/provider/gitlab'
      preLoaderRoute: typeof ProviderGitlabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/github/': {
      id: '/provider/github/'
      path: '/provider/github'
      fullPath: '/provider/github'
      preLoaderRoute: typeof ProviderGithubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slugOrId/': {
      id: '/projects/$slugOrId/'
      path: '/'
      fullPath: '/projects/$slugOrId/'
      preLoaderRoute: typeof ProjectsSlugOrIdIndexRouteImport
      parentRoute: typeof ProjectsSlugOrIdRoute
    }
    '/dev-tools/updates/': {
      id: '/dev-tools/updates/'
      path: '/dev-tools/updates'
      fullPath: '/dev-tools/updates'
      preLoaderRoute: typeof DevToolsUpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/team/': {
      id: '/dev-tools/team/'
      path: '/dev-tools/team'
      fullPath: '/dev-tools/team'
      preLoaderRoute: typeof DevToolsTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/sprints/': {
      id: '/dev-tools/sprints/'
      path: '/dev-tools/sprints'
      fullPath: '/dev-tools/sprints'
      preLoaderRoute: typeof DevToolsSprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/projects/': {
      id: '/dev-tools/projects/'
      path: '/dev-tools/projects'
      fullPath: '/dev-tools/projects'
      preLoaderRoute: typeof DevToolsProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/issues/': {
      id: '/dev-tools/issues/'
      path: '/dev-tools/issues'
      fullPath: '/dev-tools/issues'
      preLoaderRoute: typeof DevToolsIssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/analytics/': {
      id: '/dev-tools/analytics/'
      path: '/dev-tools/analytics'
      fullPath: '/dev-tools/analytics'
      preLoaderRoute: typeof DevToolsAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/gitlab/$projectId': {
      id: '/provider/gitlab/$projectId'
      path: '/provider/gitlab/$projectId'
      fullPath: '/provider/gitlab/$projectId'
      preLoaderRoute: typeof ProviderGitlabProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slugOrId/settings/': {
      id: '/projects/$slugOrId/settings/'
      path: '/settings'
      fullPath: '/projects/$slugOrId/settings'
      preLoaderRoute: typeof ProjectsSlugOrIdSettingsIndexRouteImport
      parentRoute: typeof ProjectsSlugOrIdRoute
    }
    '/projects/$slugOrId/issues/': {
      id: '/projects/$slugOrId/issues/'
      path: '/issues'
      fullPath: '/projects/$slugOrId/issues'
      preLoaderRoute: typeof ProjectsSlugOrIdIssuesIndexRouteImport
      parentRoute: typeof ProjectsSlugOrIdRoute
    }
    '/projects/$slugOrId/gitlab/': {
      id: '/projects/$slugOrId/gitlab/'
      path: '/gitlab'
      fullPath: '/projects/$slugOrId/gitlab'
      preLoaderRoute: typeof ProjectsSlugOrIdGitlabIndexRouteImport
      parentRoute: typeof ProjectsSlugOrIdRoute
    }
    '/projects/$slugOrId/github/': {
      id: '/projects/$slugOrId/github/'
      path: '/github'
      fullPath: '/projects/$slugOrId/github'
      preLoaderRoute: typeof ProjectsSlugOrIdGithubIndexRouteImport
      parentRoute: typeof ProjectsSlugOrIdRoute
    }
    '/projects/$slugOrId/analytics/': {
      id: '/projects/$slugOrId/analytics/'
      path: '/analytics'
      fullPath: '/projects/$slugOrId/analytics'
      preLoaderRoute: typeof ProjectsSlugOrIdAnalyticsIndexRouteImport
      parentRoute: typeof ProjectsSlugOrIdRoute
    }
    '/provider/github/$owner/$repo': {
      id: '/provider/github/$owner/$repo'
      path: '/provider/github/$owner/$repo'
      fullPath: '/provider/github/$owner/$repo'
      preLoaderRoute: typeof ProviderGithubOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsSlugOrIdRouteChildren {
  ProjectsSlugOrIdIndexRoute: typeof ProjectsSlugOrIdIndexRoute
  ProjectsSlugOrIdAnalyticsIndexRoute: typeof ProjectsSlugOrIdAnalyticsIndexRoute
  ProjectsSlugOrIdGithubIndexRoute: typeof ProjectsSlugOrIdGithubIndexRoute
  ProjectsSlugOrIdGitlabIndexRoute: typeof ProjectsSlugOrIdGitlabIndexRoute
  ProjectsSlugOrIdIssuesIndexRoute: typeof ProjectsSlugOrIdIssuesIndexRoute
  ProjectsSlugOrIdSettingsIndexRoute: typeof ProjectsSlugOrIdSettingsIndexRoute
}

const ProjectsSlugOrIdRouteChildren: ProjectsSlugOrIdRouteChildren = {
  ProjectsSlugOrIdIndexRoute: ProjectsSlugOrIdIndexRoute,
  ProjectsSlugOrIdAnalyticsIndexRoute: ProjectsSlugOrIdAnalyticsIndexRoute,
  ProjectsSlugOrIdGithubIndexRoute: ProjectsSlugOrIdGithubIndexRoute,
  ProjectsSlugOrIdGitlabIndexRoute: ProjectsSlugOrIdGitlabIndexRoute,
  ProjectsSlugOrIdIssuesIndexRoute: ProjectsSlugOrIdIssuesIndexRoute,
  ProjectsSlugOrIdSettingsIndexRoute: ProjectsSlugOrIdSettingsIndexRoute,
}

const ProjectsSlugOrIdRouteWithChildren =
  ProjectsSlugOrIdRoute._addFileChildren(ProjectsSlugOrIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ProjectsSlugOrIdRoute: ProjectsSlugOrIdRouteWithChildren,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  DevToolsIndexRoute: DevToolsIndexRoute,
  GithubIndexRoute: GithubIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SprintsIndexRoute: SprintsIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
  ProviderGitlabProjectIdRoute: ProviderGitlabProjectIdRoute,
  DevToolsAnalyticsIndexRoute: DevToolsAnalyticsIndexRoute,
  DevToolsIssuesIndexRoute: DevToolsIssuesIndexRoute,
  DevToolsProjectsIndexRoute: DevToolsProjectsIndexRoute,
  DevToolsSprintsIndexRoute: DevToolsSprintsIndexRoute,
  DevToolsTeamIndexRoute: DevToolsTeamIndexRoute,
  DevToolsUpdatesIndexRoute: DevToolsUpdatesIndexRoute,
  ProviderGithubIndexRoute: ProviderGithubIndexRoute,
  ProviderGitlabIndexRoute: ProviderGitlabIndexRoute,
  ProviderGithubOwnerRepoRoute: ProviderGithubOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
