/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpdatesIndexRouteImport } from './routes/updates/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as SprintsIndexRouteImport } from './routes/sprints/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as GithubIndexRouteImport } from './routes/github/index'
import { Route as DevToolsIndexRouteImport } from './routes/dev-tools/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as ProviderGitlabIndexRouteImport } from './routes/provider/gitlab/index'
import { Route as ProviderGithubIndexRouteImport } from './routes/provider/github/index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as DevToolsUpdatesIndexRouteImport } from './routes/dev-tools/updates/index'
import { Route as DevToolsTeamIndexRouteImport } from './routes/dev-tools/team/index'
import { Route as DevToolsSprintsIndexRouteImport } from './routes/dev-tools/sprints/index'
import { Route as DevToolsProjectsIndexRouteImport } from './routes/dev-tools/projects/index'
import { Route as DevToolsIssuesIndexRouteImport } from './routes/dev-tools/issues/index'
import { Route as DevToolsAnalyticsIndexRouteImport } from './routes/dev-tools/analytics/index'
import { Route as ProviderGitlabProjectIdRouteImport } from './routes/provider/gitlab/$projectId'
import { Route as ProjectsProjectIdSettingsIndexRouteImport } from './routes/projects/$projectId/settings/index'
import { Route as ProjectsProjectIdIssuesIndexRouteImport } from './routes/projects/$projectId/issues/index'
import { Route as ProjectsProjectIdGitlabIndexRouteImport } from './routes/projects/$projectId/gitlab/index'
import { Route as ProjectsProjectIdGithubIndexRouteImport } from './routes/projects/$projectId/github/index'
import { Route as ProjectsProjectIdAnalyticsIndexRouteImport } from './routes/projects/$projectId/analytics/index'
import { Route as ProviderGithubOwnerRepoRouteImport } from './routes/provider/github/$owner/$repo'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintsIndexRoute = SprintsIndexRouteImport.update({
  id: '/sprints/',
  path: '/sprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubIndexRoute = GithubIndexRouteImport.update({
  id: '/github/',
  path: '/github/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsIndexRoute = DevToolsIndexRouteImport.update({
  id: '/dev-tools/',
  path: '/dev-tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderGitlabIndexRoute = ProviderGitlabIndexRouteImport.update({
  id: '/provider/gitlab/',
  path: '/provider/gitlab/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderGithubIndexRoute = ProviderGithubIndexRouteImport.update({
  id: '/provider/github/',
  path: '/provider/github/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsUpdatesIndexRoute = DevToolsUpdatesIndexRouteImport.update({
  id: '/dev-tools/updates/',
  path: '/dev-tools/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsTeamIndexRoute = DevToolsTeamIndexRouteImport.update({
  id: '/dev-tools/team/',
  path: '/dev-tools/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsSprintsIndexRoute = DevToolsSprintsIndexRouteImport.update({
  id: '/dev-tools/sprints/',
  path: '/dev-tools/sprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsProjectsIndexRoute = DevToolsProjectsIndexRouteImport.update({
  id: '/dev-tools/projects/',
  path: '/dev-tools/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsIssuesIndexRoute = DevToolsIssuesIndexRouteImport.update({
  id: '/dev-tools/issues/',
  path: '/dev-tools/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsAnalyticsIndexRoute = DevToolsAnalyticsIndexRouteImport.update({
  id: '/dev-tools/analytics/',
  path: '/dev-tools/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderGitlabProjectIdRoute = ProviderGitlabProjectIdRouteImport.update({
  id: '/provider/gitlab/$projectId',
  path: '/provider/gitlab/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSettingsIndexRoute =
  ProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/projects/$projectId/settings/',
    path: '/projects/$projectId/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdIssuesIndexRoute =
  ProjectsProjectIdIssuesIndexRouteImport.update({
    id: '/projects/$projectId/issues/',
    path: '/projects/$projectId/issues/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdGitlabIndexRoute =
  ProjectsProjectIdGitlabIndexRouteImport.update({
    id: '/projects/$projectId/gitlab/',
    path: '/projects/$projectId/gitlab/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdGithubIndexRoute =
  ProjectsProjectIdGithubIndexRouteImport.update({
    id: '/projects/$projectId/github/',
    path: '/projects/$projectId/github/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdAnalyticsIndexRoute =
  ProjectsProjectIdAnalyticsIndexRouteImport.update({
    id: '/projects/$projectId/analytics/',
    path: '/projects/$projectId/analytics/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProviderGithubOwnerRepoRoute = ProviderGithubOwnerRepoRouteImport.update({
  id: '/provider/github/$owner/$repo',
  path: '/provider/github/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/dev-tools': typeof DevToolsIndexRoute
  '/github': typeof GithubIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sprints': typeof SprintsIndexRoute
  '/team': typeof TeamIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/provider/gitlab/$projectId': typeof ProviderGitlabProjectIdRoute
  '/dev-tools/analytics': typeof DevToolsAnalyticsIndexRoute
  '/dev-tools/issues': typeof DevToolsIssuesIndexRoute
  '/dev-tools/projects': typeof DevToolsProjectsIndexRoute
  '/dev-tools/sprints': typeof DevToolsSprintsIndexRoute
  '/dev-tools/team': typeof DevToolsTeamIndexRoute
  '/dev-tools/updates': typeof DevToolsUpdatesIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/provider/github': typeof ProviderGithubIndexRoute
  '/provider/gitlab': typeof ProviderGitlabIndexRoute
  '/provider/github/$owner/$repo': typeof ProviderGithubOwnerRepoRoute
  '/projects/$projectId/analytics': typeof ProjectsProjectIdAnalyticsIndexRoute
  '/projects/$projectId/github': typeof ProjectsProjectIdGithubIndexRoute
  '/projects/$projectId/gitlab': typeof ProjectsProjectIdGitlabIndexRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/dev-tools': typeof DevToolsIndexRoute
  '/github': typeof GithubIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sprints': typeof SprintsIndexRoute
  '/team': typeof TeamIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/provider/gitlab/$projectId': typeof ProviderGitlabProjectIdRoute
  '/dev-tools/analytics': typeof DevToolsAnalyticsIndexRoute
  '/dev-tools/issues': typeof DevToolsIssuesIndexRoute
  '/dev-tools/projects': typeof DevToolsProjectsIndexRoute
  '/dev-tools/sprints': typeof DevToolsSprintsIndexRoute
  '/dev-tools/team': typeof DevToolsTeamIndexRoute
  '/dev-tools/updates': typeof DevToolsUpdatesIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/provider/github': typeof ProviderGithubIndexRoute
  '/provider/gitlab': typeof ProviderGitlabIndexRoute
  '/provider/github/$owner/$repo': typeof ProviderGithubOwnerRepoRoute
  '/projects/$projectId/analytics': typeof ProjectsProjectIdAnalyticsIndexRoute
  '/projects/$projectId/github': typeof ProjectsProjectIdGithubIndexRoute
  '/projects/$projectId/gitlab': typeof ProjectsProjectIdGitlabIndexRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/dev-tools/': typeof DevToolsIndexRoute
  '/github/': typeof GithubIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sprints/': typeof SprintsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/provider/gitlab/$projectId': typeof ProviderGitlabProjectIdRoute
  '/dev-tools/analytics/': typeof DevToolsAnalyticsIndexRoute
  '/dev-tools/issues/': typeof DevToolsIssuesIndexRoute
  '/dev-tools/projects/': typeof DevToolsProjectsIndexRoute
  '/dev-tools/sprints/': typeof DevToolsSprintsIndexRoute
  '/dev-tools/team/': typeof DevToolsTeamIndexRoute
  '/dev-tools/updates/': typeof DevToolsUpdatesIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/provider/github/': typeof ProviderGithubIndexRoute
  '/provider/gitlab/': typeof ProviderGitlabIndexRoute
  '/provider/github/$owner/$repo': typeof ProviderGithubOwnerRepoRoute
  '/projects/$projectId/analytics/': typeof ProjectsProjectIdAnalyticsIndexRoute
  '/projects/$projectId/github/': typeof ProjectsProjectIdGithubIndexRoute
  '/projects/$projectId/gitlab/': typeof ProjectsProjectIdGitlabIndexRoute
  '/projects/$projectId/issues/': typeof ProjectsProjectIdIssuesIndexRoute
  '/projects/$projectId/settings/': typeof ProjectsProjectIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/analytics'
    | '/dev-tools'
    | '/github'
    | '/issues'
    | '/projects'
    | '/settings'
    | '/sprints'
    | '/team'
    | '/updates'
    | '/provider/gitlab/$projectId'
    | '/dev-tools/analytics'
    | '/dev-tools/issues'
    | '/dev-tools/projects'
    | '/dev-tools/sprints'
    | '/dev-tools/team'
    | '/dev-tools/updates'
    | '/projects/$projectId'
    | '/provider/github'
    | '/provider/gitlab'
    | '/provider/github/$owner/$repo'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/github'
    | '/projects/$projectId/gitlab'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/analytics'
    | '/dev-tools'
    | '/github'
    | '/issues'
    | '/projects'
    | '/settings'
    | '/sprints'
    | '/team'
    | '/updates'
    | '/provider/gitlab/$projectId'
    | '/dev-tools/analytics'
    | '/dev-tools/issues'
    | '/dev-tools/projects'
    | '/dev-tools/sprints'
    | '/dev-tools/team'
    | '/dev-tools/updates'
    | '/projects/$projectId'
    | '/provider/github'
    | '/provider/gitlab'
    | '/provider/github/$owner/$repo'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/github'
    | '/projects/$projectId/gitlab'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/analytics/'
    | '/dev-tools/'
    | '/github/'
    | '/issues/'
    | '/projects/'
    | '/settings/'
    | '/sprints/'
    | '/team/'
    | '/updates/'
    | '/provider/gitlab/$projectId'
    | '/dev-tools/analytics/'
    | '/dev-tools/issues/'
    | '/dev-tools/projects/'
    | '/dev-tools/sprints/'
    | '/dev-tools/team/'
    | '/dev-tools/updates/'
    | '/projects/$projectId/'
    | '/provider/github/'
    | '/provider/gitlab/'
    | '/provider/github/$owner/$repo'
    | '/projects/$projectId/analytics/'
    | '/projects/$projectId/github/'
    | '/projects/$projectId/gitlab/'
    | '/projects/$projectId/issues/'
    | '/projects/$projectId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  DevToolsIndexRoute: typeof DevToolsIndexRoute
  GithubIndexRoute: typeof GithubIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SprintsIndexRoute: typeof SprintsIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
  ProviderGitlabProjectIdRoute: typeof ProviderGitlabProjectIdRoute
  DevToolsAnalyticsIndexRoute: typeof DevToolsAnalyticsIndexRoute
  DevToolsIssuesIndexRoute: typeof DevToolsIssuesIndexRoute
  DevToolsProjectsIndexRoute: typeof DevToolsProjectsIndexRoute
  DevToolsSprintsIndexRoute: typeof DevToolsSprintsIndexRoute
  DevToolsTeamIndexRoute: typeof DevToolsTeamIndexRoute
  DevToolsUpdatesIndexRoute: typeof DevToolsUpdatesIndexRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProviderGithubIndexRoute: typeof ProviderGithubIndexRoute
  ProviderGitlabIndexRoute: typeof ProviderGitlabIndexRoute
  ProviderGithubOwnerRepoRoute: typeof ProviderGithubOwnerRepoRoute
  ProjectsProjectIdAnalyticsIndexRoute: typeof ProjectsProjectIdAnalyticsIndexRoute
  ProjectsProjectIdGithubIndexRoute: typeof ProjectsProjectIdGithubIndexRoute
  ProjectsProjectIdGitlabIndexRoute: typeof ProjectsProjectIdGitlabIndexRoute
  ProjectsProjectIdIssuesIndexRoute: typeof ProjectsProjectIdIssuesIndexRoute
  ProjectsProjectIdSettingsIndexRoute: typeof ProjectsProjectIdSettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprints/': {
      id: '/sprints/'
      path: '/sprints'
      fullPath: '/sprints'
      preLoaderRoute: typeof SprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/': {
      id: '/github/'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/': {
      id: '/dev-tools/'
      path: '/dev-tools'
      fullPath: '/dev-tools'
      preLoaderRoute: typeof DevToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/gitlab/': {
      id: '/provider/gitlab/'
      path: '/provider/gitlab'
      fullPath: '/provider/gitlab'
      preLoaderRoute: typeof ProviderGitlabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/github/': {
      id: '/provider/github/'
      path: '/provider/github'
      fullPath: '/provider/github'
      preLoaderRoute: typeof ProviderGithubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/updates/': {
      id: '/dev-tools/updates/'
      path: '/dev-tools/updates'
      fullPath: '/dev-tools/updates'
      preLoaderRoute: typeof DevToolsUpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/team/': {
      id: '/dev-tools/team/'
      path: '/dev-tools/team'
      fullPath: '/dev-tools/team'
      preLoaderRoute: typeof DevToolsTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/sprints/': {
      id: '/dev-tools/sprints/'
      path: '/dev-tools/sprints'
      fullPath: '/dev-tools/sprints'
      preLoaderRoute: typeof DevToolsSprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/projects/': {
      id: '/dev-tools/projects/'
      path: '/dev-tools/projects'
      fullPath: '/dev-tools/projects'
      preLoaderRoute: typeof DevToolsProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/issues/': {
      id: '/dev-tools/issues/'
      path: '/dev-tools/issues'
      fullPath: '/dev-tools/issues'
      preLoaderRoute: typeof DevToolsIssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/analytics/': {
      id: '/dev-tools/analytics/'
      path: '/dev-tools/analytics'
      fullPath: '/dev-tools/analytics'
      preLoaderRoute: typeof DevToolsAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/gitlab/$projectId': {
      id: '/provider/gitlab/$projectId'
      path: '/provider/gitlab/$projectId'
      fullPath: '/provider/gitlab/$projectId'
      preLoaderRoute: typeof ProviderGitlabProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/settings/': {
      id: '/projects/$projectId/settings/'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/issues/': {
      id: '/projects/$projectId/issues/'
      path: '/projects/$projectId/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof ProjectsProjectIdIssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/gitlab/': {
      id: '/projects/$projectId/gitlab/'
      path: '/projects/$projectId/gitlab'
      fullPath: '/projects/$projectId/gitlab'
      preLoaderRoute: typeof ProjectsProjectIdGitlabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/github/': {
      id: '/projects/$projectId/github/'
      path: '/projects/$projectId/github'
      fullPath: '/projects/$projectId/github'
      preLoaderRoute: typeof ProjectsProjectIdGithubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/analytics/': {
      id: '/projects/$projectId/analytics/'
      path: '/projects/$projectId/analytics'
      fullPath: '/projects/$projectId/analytics'
      preLoaderRoute: typeof ProjectsProjectIdAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/github/$owner/$repo': {
      id: '/provider/github/$owner/$repo'
      path: '/provider/github/$owner/$repo'
      fullPath: '/provider/github/$owner/$repo'
      preLoaderRoute: typeof ProviderGithubOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  DevToolsIndexRoute: DevToolsIndexRoute,
  GithubIndexRoute: GithubIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SprintsIndexRoute: SprintsIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
  ProviderGitlabProjectIdRoute: ProviderGitlabProjectIdRoute,
  DevToolsAnalyticsIndexRoute: DevToolsAnalyticsIndexRoute,
  DevToolsIssuesIndexRoute: DevToolsIssuesIndexRoute,
  DevToolsProjectsIndexRoute: DevToolsProjectsIndexRoute,
  DevToolsSprintsIndexRoute: DevToolsSprintsIndexRoute,
  DevToolsTeamIndexRoute: DevToolsTeamIndexRoute,
  DevToolsUpdatesIndexRoute: DevToolsUpdatesIndexRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProviderGithubIndexRoute: ProviderGithubIndexRoute,
  ProviderGitlabIndexRoute: ProviderGitlabIndexRoute,
  ProviderGithubOwnerRepoRoute: ProviderGithubOwnerRepoRoute,
  ProjectsProjectIdAnalyticsIndexRoute: ProjectsProjectIdAnalyticsIndexRoute,
  ProjectsProjectIdGithubIndexRoute: ProjectsProjectIdGithubIndexRoute,
  ProjectsProjectIdGitlabIndexRoute: ProjectsProjectIdGitlabIndexRoute,
  ProjectsProjectIdIssuesIndexRoute: ProjectsProjectIdIssuesIndexRoute,
  ProjectsProjectIdSettingsIndexRoute: ProjectsProjectIdSettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
